
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWk45alJ2Tng4ZE13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBM01EY3hPREk1TkRoYUZ3MHpOVEEzTURVeE9ETTBORGhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURCZmR6bm5mUTI5eDhxNFhKUmJSeFpDUXZnZHZIaUlxbm9zZ2V4eHZFQ0tLZGM0WG1Va3JWcmhXR1YKYVNHcm0vMmUrSlNrbVdndk9qTGM0ajNYR0JOaGdMUlB0MEVKbUc3RGNZaXNRY1p0UmoxSGoxWlFwS09wVGhRUQpiQXQ5R0dTREU4aFBwRzkzS1VTN3FpbGlnNEs1SnZNY2pBT0JDZ25zWG9pTzBsWnRsTG40MHp6QURwR1FOdGdyCmJEck1Sa0UzK1M1RkZmbW5jK2w3K2J3cmdDYW9JcFQ1OGRsdnlnY3Q1cHVhenZtT08vYkx1aENxN2g0c1lHdXYKZWl5YzFqN1NneENLZHhwWlpRaFU5c2J3USt6RjFWUE81Y2R6aDFPWmd5MGpKVEhpRlhFZkxVQUpYakZTbUFtNQpKUE5yZmNLR25wc0l1Q0Q4eWNLYm5INndTWTJkQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTSWdKRXY0L1pkOUc1YWhrU082aVl3dlZUNzNEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQzFjRFRTYUJkYgpyYlVnOTVxT2ZUUHVUUzdla05sWXhPcVl4Qmc3aCs4bWpSTTA4NXlLV2R6SlZHNVlNeDFIMkJUcHg3aHY3UmNJCjYraFk1NjZIOXVWelZabWhxRW9rRWJPMk9IeW9EK2ZmVlFkcXgwM0oxZEhKSG56UTJhTlJ4bkNiRk5UK3FKNFQKWW0vS2xiM2pkcTQ0U0VHUWhlcHF3Y1ovbVRNSkYwZlBtQ2R5b1pkaE1aVDc0ZVp4dngxUDNMMGpDcHJLcURsOQovZW5SaXJ4b0JXdWRBM2VYV3FOc3d5SjF4TDlPdXpVT3FzeExEc0hoYmJUWGFjNFNEc3pROURSY3JUMGVRVENsClQzRTNtUUVYZW54aG5lSW5WcDRMczcwRmxoUDI3bGRTQVdSbmRhNHVrV3BMZXZNc0VMdEl6MWsvc0RIaE1OeWUKNUU3S01aVjFXWm5BCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://3e20d2fb-ed8d-47d4-b719-d8b1f31e140e.us-mia-1-gw.linodelke.net:443
  name: lke496587

users:
- name: lke496587-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlZXMEJIclFQdi00NjhLTl90ckFveUxLUS10dXR5YXhzNzZwU3FkcFYxY1EifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tcGpoYm0iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZDY3N2E4NTAtMDdjMC00ZTYxLTg0NzgtNDg4YmZmYTAwOTMyIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.ggAULoqegkblzlTHmOSOMck3nmPGE1NY3gkMw7dRDEMJJhFUUnSVfk1FMcJ0TrKa_uLxeI09AogUIohc2A1bZMkTfz3ASWVx061LLFoVwwrh2mL-baaVfzC6khU2U15-JmWicW1A0vNE68uTA1RnHVjV-6TLW0pkGbkRpLM_rlwqPCwNwwCJvtxk9sWeiQnWT-uW3t2Sdco66AVQ_8aggVqU5aaU2YahV4rqJkwoekhI7QMM1ZMQY2avTl_J6I6ZApPeSpO6uu6CKqrG6BVoqh15x_7M53N9hh7iqo1yep1Yss4qUXYv6pZ_JLEsYw3OHxqCIZmZM53TqC-rB38Stg

contexts:
- context:
    cluster: lke496587
    namespace: default
    user: lke496587-admin
  name: lke496587-ctx

current-context: lke496587-ctx
